apiVersion: apps/v1
kind: Deployment 
metadata:
  name: go-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate  # default deployment strategy
    rollingUpdate:
      maxUnavailable: 0  # Ensure no downtime (0 pods can be unavailable during update)
      maxSurge: 1        # Allow only 1 extra pod above desired replicas during update
  selector:
    matchLabels:
      app: go  # stateless (different services should have different deployments)
  template:
    metadata:
      name: go-pod
      labels:
        app: go
        type: stateless
    spec:
      #imagePullSecrets:
      #- name: my-credentials  # log into ECR
      containers:
      - name: go
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # provide full path if pulling from ECR
        imagePullPolicy: {{ .Values.image.pullPolicy }}  # "Always" (prod) tries to pull go-app:latest from Docker Hub rather than KinD
        envFrom:  # environment variables
        - configMapRef:
            name: redis-config  # kubectl create -f redis-config.yaml
        - configMapRef:
            name: main-config  # kubectl create -f main-config.yaml
        #- secretRef:
        #    name: app-secret
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        readinessProbe:  # Ensure app is ready before marking as available
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:  # Ensure app is healthy, else restart pod
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:  # requests without limits are the most flexible
            cpu: "250m"   # Request 0.25 CPU cores
            memory: "128Mi"  # Request 128MB RAM
          limits:
            cpu: "500m"   # Limit to 0.5 CPU cores
            memory: "256Mi"  # Limit to 256MB RAM

---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: {{ .Values.service.type }}  # uses Random algorithm for load balancing
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: 30004  # optional
  selector:
    app: go  # this is how we connect the service to a specific pod
    type: stateless