apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding  # links a User to a Role (scoped at the cluster level)
metadata:
  name: cluster-admin-binding
subjects:
- kind: User
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io