apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition  # without a custom controller, this resource is simply stored in ETCD
metadata:
  name: aws.resource.com
spec:
  scope: Namespaced
  group: resource.com
  names:
    kind: MyResource
    singular: myresource
    plural: myresources
    shortnames:
      - mr
  versions:
    - name: v1
      served: true
      storage: true
  schema:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            from:
              type: string
            to:
              type: string
            number:
              type: integer
              minimum: 1
              maximum: 10