apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:  # requires metrics server running (or an external adapter such as Dynatrace)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50