apiVersion: batch/v1
kind: Job
metadata:
  name: go-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "echo Processing item; sleep 30"]
      restartPolicy: Never