apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: split-traffic-canary
spec:
  parentRefs:
  - name: first-gateway
  hostnames:
  - "www.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /login
    backendRefs:
    - name: first-service
      port: 8080
      weight: 80
    - name: second-service
      port: 8080
      weight: 20