apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv  # 1:1 relationship between volumes and claims
spec:
  accessModes:
    - ReadWriteOnce  # ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle  # Retain (default), Delete
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4
  #hostPath:  # do not use in production
  #  path: /tmp/data