apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pvc  # we can choose a specific class of storage (i.e. Bronze, Silver, Gold)
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-storage  # must match the StorageClass name
  resources:
    requests:
      storage: 500Mi
  # storageClassName: default  # DefaultStorageClass mutating admission controller enabled by default