apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 100000
globalDefault: false
description: "kube-scheduler: This priority class is used for services (i.e. Redis) that the main application depends on."