apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: go-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: go-deployment
  updatePolicy:
    updateMode: "Auto"  # automatic updates
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
        maxAllowed:
          cpu: 1000m
        controlledResources: ["cpu"]