name: Go with Kubernetes CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./... -v

  deploy-kubernetes:
    needs: test  # Only deploy if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up KinD (Kubernetes-in-Docker)
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind-cluster

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Verify Kubernetes Cluster
        run: kubectl get nodes

      - name: Build Docker Image
        run: |
          docker build -t go-app:latest .

      - name: Load Image into KinD Cluster
        run: |
          kind load docker-image go-app:latest --name kind-cluster

      - name: Apply Kubernetes Manifests
        run: |
          kubectl label node kind-cluster-control-plane size=Large
          kubectl apply -f k8s/redis-config.yaml
          kubectl apply -f k8s/main-config.yaml
          kubectl apply -f k8s/priority-class.yaml
          kubectl apply -f k8s/redis-deployment.yaml
          kubectl apply -f k8s/go-deployment.yaml

      - name: Wait for Pods to be Ready
        run: kubectl wait --for=condition=Ready pod --all --timeout=90s

      - name: Verify Deployment
        run: kubectl get pods -A

      - name: Test API Endpoint
        run: |
          sleep 5  # Allow time for app to start
          kubectl port-forward svc/go-service 8000:80 &
          sleep 3
          curl -X POST "http://localhost:8000/set/?key=username&value=JohnDoe"
          curl "http://localhost:8000/get/username"
          curl --retry 5 --retry-delay 2 --fail http://localhost:8000/ || (kubectl logs deployment/go-deployment && exit 1)
